name: Build OpenWrt ARM64

on:
  push:
  workflow_dispatch:

jobs:
  build-aarch64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            gcc-aarch64-linux-gnu \
            musl-tools

      - name: Install Rust target
        run: rustup target add aarch64-unknown-linux-musl

      - name: Configure Cargo
        run: |
          mkdir -p .cargo

          cat > .cargo/config.toml << 'EOF'
          [target.aarch64-unknown-linux-musl]
          linker = "aarch64-linux-gnu-gcc"

          [profile.release]
          lto = true
          codegen-units = 1
          panic = "abort"
          strip = true
          EOF

      - name: Build binary
        run: |
          cargo build \
            --release \
            --target aarch64-unknown-linux-musl

      - name: Show release files
        run: |
          ls -lah target/aarch64-unknown-linux-musl/release/

      - name: Find binary
        run: |
          BIN=$(find target/aarch64-unknown-linux-musl/release \
            -maxdepth 1 \
            -type f \
            -executable \
            ! -name "*.d" \
            | head -n 1)

          echo "Binary found:"
          echo "$BIN"

          echo "BIN_PATH=$BIN" >> $GITHUB_ENV

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-aarch64-binary
          path: ${{ env.BIN_PATH }}
